controller:
  replicaCount: 3
  config:
    cipher-suite: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
    ssl-protocols: "TLSv1.2 TLSv1.3"
    use-forwarded-headers: "true"
    enable-owasp-modsecurity-crs: "true"

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:123456789012:certificate/quantum-cert"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tls"

tcp:
  2222: "default/deception-ssh:22"

modsecurity:
  enabled: true
  secRuleEngine: "On"
  secRequestBodyAccess: "On"
  secResponseBodyAccess: "On"
  secRules: |
    Include @owasp_crs/*.conf
    SecRuleEngine On
    SecDefaultAction "phase:1,log,auditlog,deny,status:403"
